WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
TRANSPARENT = (0, 255, 0)

AMBULANCE_RED = (250, 3, 0)
HOMUNCULUS_ORANGE = (255, 173, 0)

ORANGE_TEXT = (223, 153, 0)

INCIDENT_EFFECTS = 0
INCIDENT_FAST = 1
INCIDENT_ALLERGENS = 2
INCIDENT_EFFECTS_ALLERGENS = 3
INCIDENT_EFFECTS_HARD = 4
INCIDENT_EFFECTS_ALLERGENS_HARD = 5
INCIDENT_FASTER = 6
INCIDENT_EFFECTS_BRANDS = 7
INCIDENT_EFFECTS_ALLERGENS_BRANDS = 8
INCIDENT_EFFECTS_BOOTLEGS = 9
INCIDENT_EFFECTS_VERIFICATION = 10
INCIDENT_EFFECTS_ALTERNATION = 11

LEFT = 0
RIGHT = 1
