WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
TRANSPARENT = (0, 255, 0)

AMBULANCE_RED = (250, 3, 0)
HOMUNCULUS_ORANGE = (255, 173, 0)

ORANGE_TEXT = (223, 153, 0)

EFFECTS_INCIDENT = 0
FAST_INCIDENT = 1
ALLERGENS_INCIDENT = 2
EFFECTS_ALLERGENS_INCIDENT = 3
EFFECTS_HARD_INCIDENT = 4
EFFECTS_ALLERGENS_HARD_INCIDENT = 5
FASTER_INCIDENT = 6
EFFECTS_BRANDS_INCIDENT = 7
EFFECTS_ALLERGENS_BRANDS_INCIDENT = 8
EFFECTS_BOOTLEGS_INCIDENT = 9
EFFECTS_VERIFICATION_INCIDENT = 10
EFFECTS_ALTERNATION_INCIDENT = 11

LEFT = 0
RIGHT = 1
